# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Thu Jun 04 18:40:05 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(689, 538)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLineEdit(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 431, 21))
        self.label.setReadOnly(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(450, 154, 160, 61))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hght = QtGui.QLabel(self.gridLayoutWidget)
        self.hght.setText(_fromUtf8(""))
        self.hght.setObjectName(_fromUtf8("hght"))
        self.gridLayout.addWidget(self.hght, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.wdth = QtGui.QLabel(self.gridLayoutWidget)
        self.wdth.setText(_fromUtf8(""))
        self.wdth.setObjectName(_fromUtf8("wdth"))
        self.gridLayout.addWidget(self.wdth, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(450, 8, 160, 57))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.saveFileList = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.saveFileList.setObjectName(_fromUtf8("saveFileList"))
        self.gridLayout_2.addWidget(self.saveFileList, 1, 1, 1, 1)
        self.selectFolder = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.selectFolder.setObjectName(_fromUtf8("selectFolder"))
        self.gridLayout_2.addWidget(self.selectFolder, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(450, 474, 160, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_4 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.saveLog = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.saveLog.setObjectName(_fromUtf8("saveLog"))
        self.horizontalLayout.addWidget(self.saveLog)
        self.errorEdit = QtGui.QTextEdit(self.centralwidget)
        self.errorEdit.setGeometry(QtCore.QRect(10, 370, 431, 140))
        self.errorEdit.setReadOnly(True)
        self.errorEdit.setObjectName(_fromUtf8("errorEdit"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(10, 330, 431, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(450, 234, 181, 91))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.prw = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.prw.setEnabled(True)
        self.prw.setDecimals(1)
        self.prw.setMinimum(1.0)
        self.prw.setMaximum(10.0)
        self.prw.setSingleStep(0.5)
        self.prw.setObjectName(_fromUtf8("prw"))
        self.gridLayout_3.addWidget(self.prw, 1, 1, 1, 1)
        self.run = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.run.setEnabled(False)
        self.run.setObjectName(_fromUtf8("run"))
        self.gridLayout_3.addWidget(self.run, 2, 2, 1, 1)
        self.demo = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.demo.setEnabled(False)
        self.demo.setObjectName(_fromUtf8("demo"))
        self.gridLayout_3.addWidget(self.demo, 1, 2, 1, 1)
        self.fps = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.fps.setEnabled(True)
        self.fps.setDecimals(0)
        self.fps.setMinimum(1.0)
        self.fps.setMaximum(48.0)
        self.fps.setProperty("value", 24.0)
        self.fps.setObjectName(_fromUtf8("fps"))
        self.gridLayout_3.addWidget(self.fps, 2, 1, 1, 1)
        self.check = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.check.setEnabled(False)
        self.check.setObjectName(_fromUtf8("check"))
        self.gridLayout_3.addWidget(self.check, 0, 1, 1, 2)
        self.logEdit = QtGui.QTextEdit(self.centralwidget)
        self.logEdit.setGeometry(QtCore.QRect(10, 40, 431, 281))
        self.logEdit.setReadOnly(True)
        self.logEdit.setObjectName(_fromUtf8("logEdit"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(450, 76, 160, 63))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.total = QtGui.QLabel(self.gridLayoutWidget_4)
        self.total.setText(_fromUtf8(""))
        self.total.setObjectName(_fromUtf8("total"))
        self.gridLayout_4.addWidget(self.total, 0, 1, 1, 1)
        self.len = QtGui.QLabel(self.gridLayoutWidget_4)
        self.len.setText(_fromUtf8(""))
        self.len.setObjectName(_fromUtf8("len"))
        self.gridLayout_4.addWidget(self.len, 1, 1, 1, 1)
        self.doneText = QtGui.QLabel(self.centralwidget)
        self.doneText.setGeometry(QtCore.QRect(450, 338, 46, 13))
        self.doneText.setText(_fromUtf8(""))
        self.doneText.setObjectName(_fromUtf8("doneText"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.errorEdit.selectAll)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.logEdit.selectAll)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.logEdit.copy)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.errorEdit.copy)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.logEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_3.setText(_translate("MainWindow", "Выcота:", None))
        self.label_4.setText(_translate("MainWindow", "Ширина:", None))
        self.pushButton.setText(_translate("MainWindow", "×", None))
        self.saveFileList.setText(_translate("MainWindow", "Сохр", None))
        self.selectFolder.setText(_translate("MainWindow", "Обзор", None))
        self.pushButton_2.setText(_translate("MainWindow", "Копир", None))
        self.pushButton_4.setText(_translate("MainWindow", "Копир", None))
        self.saveLog.setText(_translate("MainWindow", "Сохр", None))
        self.run.setText(_translate("MainWindow", "Запуск", None))
        self.demo.setText(_translate("MainWindow", "Демо", None))
        self.check.setText(_translate("MainWindow", "Проверить", None))
        self.logEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "Всего кадров", None))
        self.label_6.setText(_translate("MainWindow", "Длина трека", None))

