# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Tue Jun 16 16:35:22 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(561, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLineEdit(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 430, 21))
        self.label.setReadOnly(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.errorEdit = QtGui.QTextEdit(self.centralwidget)
        self.errorEdit.setGeometry(QtCore.QRect(10, 336, 430, 140))
        self.errorEdit.setReadOnly(True)
        self.errorEdit.setObjectName(_fromUtf8("errorEdit"))
        self.logEdit = QtGui.QTextEdit(self.centralwidget)
        self.logEdit.setGeometry(QtCore.QRect(10, 40, 430, 281))
        self.logEdit.setReadOnly(True)
        self.logEdit.setObjectName(_fromUtf8("logEdit"))
        self.demo = QtGui.QPushButton(self.centralwidget)
        self.demo.setEnabled(False)
        self.demo.setGeometry(QtCore.QRect(500, 240, 51, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demo.sizePolicy().hasHeightForWidth())
        self.demo.setSizePolicy(sizePolicy)
        self.demo.setObjectName(_fromUtf8("demo"))
        self.prw = QtGui.QDoubleSpinBox(self.centralwidget)
        self.prw.setEnabled(True)
        self.prw.setGeometry(QtCore.QRect(450, 240, 41, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prw.sizePolicy().hasHeightForWidth())
        self.prw.setSizePolicy(sizePolicy)
        self.prw.setFrame(True)
        self.prw.setDecimals(1)
        self.prw.setMinimum(1.0)
        self.prw.setMaximum(10.0)
        self.prw.setSingleStep(0.5)
        self.prw.setObjectName(_fromUtf8("prw"))
        self.check = QtGui.QPushButton(self.centralwidget)
        self.check.setEnabled(False)
        self.check.setGeometry(QtCore.QRect(500, 298, 51, 23))
        self.check.setObjectName(_fromUtf8("check"))
        self.fps = QtGui.QDoubleSpinBox(self.centralwidget)
        self.fps.setEnabled(True)
        self.fps.setGeometry(QtCore.QRect(450, 270, 41, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fps.sizePolicy().hasHeightForWidth())
        self.fps.setSizePolicy(sizePolicy)
        self.fps.setDecimals(0)
        self.fps.setMinimum(1.0)
        self.fps.setMaximum(48.0)
        self.fps.setProperty("value", 24.0)
        self.fps.setObjectName(_fromUtf8("fps"))
        self.run = QtGui.QPushButton(self.centralwidget)
        self.run.setEnabled(False)
        self.run.setGeometry(QtCore.QRect(500, 270, 51, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run.sizePolicy().hasHeightForWidth())
        self.run.setSizePolicy(sizePolicy)
        self.run.setObjectName(_fromUtf8("run"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 175, 21, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.doneText = QtGui.QLineEdit(self.centralwidget)
        self.doneText.setGeometry(QtCore.QRect(450, 300, 41, 20))
        self.doneText.setAlignment(QtCore.Qt.AlignCenter)
        self.doneText.setReadOnly(True)
        self.doneText.setObjectName(_fromUtf8("doneText"))
        self.len = QtGui.QLineEdit(self.centralwidget)
        self.len.setGeometry(QtCore.QRect(450, 145, 41, 20))
        self.len.setAlignment(QtCore.Qt.AlignCenter)
        self.len.setReadOnly(True)
        self.len.setObjectName(_fromUtf8("len"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 145, 21, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.secondsLen = QtGui.QLineEdit(self.centralwidget)
        self.secondsLen.setGeometry(QtCore.QRect(510, 145, 41, 20))
        self.secondsLen.setAlignment(QtCore.Qt.AlignCenter)
        self.secondsLen.setReadOnly(True)
        self.secondsLen.setObjectName(_fromUtf8("secondsLen"))
        self.wdth = QtGui.QLineEdit(self.centralwidget)
        self.wdth.setGeometry(QtCore.QRect(450, 175, 41, 20))
        self.wdth.setAlignment(QtCore.Qt.AlignCenter)
        self.wdth.setReadOnly(True)
        self.wdth.setObjectName(_fromUtf8("wdth"))
        self.hght = QtGui.QLineEdit(self.centralwidget)
        self.hght.setGeometry(QtCore.QRect(510, 175, 41, 20))
        self.hght.setAlignment(QtCore.Qt.AlignCenter)
        self.hght.setReadOnly(True)
        self.hght.setObjectName(_fromUtf8("hght"))
        self.total = QtGui.QLineEdit(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(450, 115, 101, 20))
        self.total.setAlignment(QtCore.Qt.AlignCenter)
        self.total.setReadOnly(True)
        self.total.setObjectName(_fromUtf8("total"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 480, 100, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 39, 46, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.saveFileList = QtGui.QPushButton(self.centralwidget)
        self.saveFileList.setGeometry(QtCore.QRect(505, 39, 46, 23))
        self.saveFileList.setObjectName(_fromUtf8("saveFileList"))
        self.selectFolder = QtGui.QPushButton(self.centralwidget)
        self.selectFolder.setGeometry(QtCore.QRect(450, 9, 46, 23))
        self.selectFolder.setObjectName(_fromUtf8("selectFolder"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(505, 9, 46, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 454, 46, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.saveLog = QtGui.QPushButton(self.centralwidget)
        self.saveLog.setGeometry(QtCore.QRect(505, 454, 46, 23))
        self.saveLog.setObjectName(_fromUtf8("saveLog"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.errorEdit.selectAll)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.logEdit.selectAll)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.logEdit.copy)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.errorEdit.copy)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.logEdit.clear)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.errorEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "0x0000FF01", None))
        self.logEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.demo.setText(_translate("MainWindow", "D", None))
        self.check.setText(_translate("MainWindow", "T", None))
        self.run.setText(_translate("MainWindow", ">>>>", None))
        self.label_2.setText(_translate("MainWindow", "×", None))
        self.label_3.setText(_translate("MainWindow", ":", None))
        self.pushButton_2.setText(_translate("MainWindow", "C", None))
        self.saveFileList.setText(_translate("MainWindow", "S", None))
        self.selectFolder.setText(_translate("MainWindow", "+", None))
        self.pushButton.setText(_translate("MainWindow", "×", None))
        self.pushButton_4.setText(_translate("MainWindow", "C", None))
        self.saveLog.setText(_translate("MainWindow", "S", None))

